sudo: false
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.22
      - ghc-7.10.3
      - happy-1.19.3
      - alex-3.1.3
      - mono-devel
      - mono-utils
before_install:
- export PATH=/opt/ghc/7.10.3/bin:/opt/alex/3.1.3/bin:/opt/happy/1.19.3/bin:/opt/cabal/1.22/bin:/home/travis/.cabal/bin:$PATH
install:
- cabal update
- git clone --depth 1 https://github.com/idris-lang/Idris-dev.git vendor/idris
- git clone --depth 1 https://github.com/bamboo/language-cil.git --branch idris-cil --single-branch vendor/language-cil
script:
- cd vendor/language-cil && cabal install --only-dependencies -j2 && cabal install
- cd ../idris && cabal install --only-dependencies -j2 && cabal configure && cabal install -j2 --disable-documentation
# - cd ../../ciltree
# - cabal install --only-dependencies --enable-tests -j2 && cabal configure --enable-tests
# - cabal test --show-details=streaming --test-options="--color" -j2
- cd ../../rts
- idris --install cil.ipkg
- cd ../codegen
- cabal install --only-dependencies --enable-tests -j2 && cabal configure --enable-tests
- cabal build && cabal test --show-details=streaming --test-options="--color" -j2
