sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
    - ~/.stack
    - ~/.local
  apt: true

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.3
      - mono-devel
      - mono-utils

before_install:
  # Add ghc to the PATH
  - export PATH=/opt/ghc/7.10.3/bin:$PATH
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - curl -L https://raw.githubusercontent.com/futurice/fum2github/3a270cf7a3b600900c1a8ed07c23d5f3ba8b115d/travis_long > travis_long && chmod +x travis_long

script:
  - cd codegen
  - ../travis_long stack --no-terminal --skip-ghc-check install idris --verbose
  - cd ../rts && idris --install cil.ipkg && cd ../codegen
  - stack --no-terminal --skip-ghc-check test --verbose
