resolver: lts-8.13
packages:
  - location: .
  - location:
      git: https://github.com/bamboo/language-cil.git
      commit: 0438ed5173c9d0ddeb55f315464f5e9fec6c1731
    extra-dep: true
  - location:
      git: https://github.com/idris-lang/Idris-dev.git
      commit: ffd2db0b307707dee923c4ae9b7b0448037188df
    extra-dep: true
flags:
  idris:
    ffi: true
extra-deps:
  - libffi-0.1
