resolver: lts-8.13
packages:
  - location: .
  - location:
      git: https://github.com/bamboo/language-cil.git
      commit: 0438ed5173c9d0ddeb55f315464f5e9fec6c1731
    extra-dep: true
  - location:
      git: https://github.com/idris-lang/Idris-dev.git
      commit: fcbabc28343ca9fa159f6d7db3fc7bd20ca45dc9
    extra-dep: true
flags:
  idris:
    ffi: true
extra-deps:
  - libffi-0.1
