resolver: lts-7.0
packages:
  - location: .
  - location:
      git: https://github.com/bamboo/language-cil.git
      commit: 3f343e48e89d08ba222f4d3091b7a06922301b14
    extra-dep: true
flags:
  idris:
    ffi: true
extra-deps:
  - bool-extras-0.4.0
  - idris-0.12.3
  - libffi-0.1
