resolver: lts-8.8
packages:
  - location: .
  - location:
      git: https://github.com/bamboo/language-cil.git
      commit: 0438ed5173c9d0ddeb55f315464f5e9fec6c1731
    extra-dep: true
  - location:
      git: https://github.com/idris-lang/Idris-dev.git
      commit: 385f84850f169756c1de651b3061dddb3fede756
    extra-dep: true
flags:
  idris:
    ffi: true
extra-deps:
  - bool-extras-0.4.0
  - libffi-0.1
