resolver: lts-8.17
packages:
  - location: .
  - location:
      git: https://github.com/bamboo/language-cil.git
      commit: 0438ed5173c9d0ddeb55f315464f5e9fec6c1731
    extra-dep: true
  - location:
      git: https://github.com/idris-lang/Idris-dev.git
      commit: ea2041c47e20ae62341224ee8b36f680efb646a5
    extra-dep: true
flags:
  idris:
    ffi: true
extra-deps:
  - libffi-0.1
