resolver: lts-7.0
packages:
  - location: .
  - location:
      git: https://github.com/bamboo/language-cil.git
      commit: 60076ab304c4d83de9d3ca075e4abfb1b0b66385
    extra-dep: true
flags:
  idris:
    ffi: true
extra-deps:
  - bool-extras-0.4.0
  - idris-0.12.3
  - libffi-0.1
